services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: finsol-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [finsol]

  redis:
    image: redis:7-alpine
    container_name: finsol-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [finsol]

  producer:
    build:
      context: .
      dockerfile: docker/Dockerfile.producer
    container_name: finsol-producer
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [finsol]

  notification:
    build:
      context: .
      dockerfile: docker/Dockerfile.notification
    container_name: finsol-notification
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [finsol]

networks:
  finsol:
    driver: bridge
